# Generated by Django 4.2.16 on 2024-12-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_comment_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited',
        ),
    ]
