# Generated by Django 4.2.16 on 2024-12-10 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_projectposts_projectpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0005_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='image',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
