# Generated by Django 4.2.16 on 2024-12-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
