# Generated by Django 4.2.16 on 2024-11-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_brand_project_make_rename_name_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
