# Generated by Django 4.2.16 on 2024-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectimages_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
