# Generated by Django 4.2.16 on 2024-12-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_follower'),
        ('projects', '0005_alter_project_description_alter_project_horsepower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectPosts',
        ),
    ]
