# Generated by Django 4.2.16 on 2024-12-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_projectimages_projectposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.project'),
        ),
    ]
