# Generated by Django 4.2.16 on 2024-12-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectposts_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='make',
            new_name='brand',
        ),
    ]
