# Generated by Django 4.2.16 on 2024-12-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_follower'),
        ('projects', '0008_rename_make_project_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPosts',
            new_name='ProjectPost',
        ),
    ]
